version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - elk-net

  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.0
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5044:5044"
    depends_on:
      - elasticsearch
    networks:
      - elk-net

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk-net

  # json-uploader:
  #   build:
  #     context: ./rust-json-uploader
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - elasticsearch
  #   volumes:
  #     - ./data:/data
  #   environment:
  #     - ES_HOST=elasticsearch
  #   networks:
  #     - elk-net

networks:
  elk-net:
    driver: bridge
